---
- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: true

- name: Reset UFW to default
  ufw:
    state: reset

- name: Set UFW default policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }

- name: Allow SSH (port 22)
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
    comment: "SSH access"

- name: Allow HTTP (port 80)
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp
    comment: "HTTP access"

- name: Allow HTTPS (port 443)
  ufw:
    rule: allow
    port: "{{ https_port }}"
    proto: tcp
    comment: "HTTPS access"

- name: Enable UFW
  ufw:
    state: enabled
    loglevel: low

- name: Show UFW status
  command: ufw status verbose
  register: ufw_status
  changed_when: false

- name: Display UFW status
  debug:
    var: ufw_status.stdout_lines 